# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base_case_2019:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-07 00:00
  time_step: 1h
  industrial_dsm_units: null
  save_frequency_hours: 720

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2019-01-01 00:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

  learning_config: 
    learning_mode: True
    continue_learning: false
    trained_policies_save_path: null
    min_bid_price: 10
    max_bid_price: 315
    algorithm: matd3
    learning_rate: 0.0001
    learning_rate_schedule: linear
    training_episodes: 75
    episodes_collecting_initial_experience: 20
    train_freq: 24h
    gradient_steps: 1
    batch_size: 128
    gamma: 0.99
    device: cuda:0
    action_noise_schedule: linear
    noise_sigma: 0.2
    noise_scale: 1
    noise_dt: 0.9
    validation_episodes_interval: 5
    early_stopping_steps: 2
    early_stopping_threshold: 0.05